name: CI/CD Pipeline for FastAPI

on:
  push:
    branches:
      - pilot  # Trigger deployment when code is pushed to dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Kill existing process on port 8000
        run: |
          sudo fuser -k 8000/tcp || true  # Kill any existing process

      - name: Set up SSH
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.PILOT_HOST }} >> ~/.ssh/known_hosts


      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PILOT_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/r2_api
            git reset --hard
            git pull origin pilot
            source r2dev/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
            sudo systemctl status fastapi
