"""
Django settings for playergame_poc project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

#from decouple import config
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=%0@02d26820!4c7g*v88$y2z_s&y6snno*69#=*u&%qj8z60%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'drf_yasg',
    'django_extensions',

    # Your app
    'playergameSearch',
    'corsheaders',
    'usermanagement'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "admin@alonzoai.in"
EMAIL_HOST_PASSWORD = "knvj ravx gugn mwgf"
#CORS_ALLOW_CREDENTIALS  = True
#CORS_ORIGIN_ALLOW_ALL = True

#CSRF_TRUSTED_ORIGINS = [
#    "https://dev.athlytesports.com",
#    "http://localhost:3000",
#    "https://dev-srv.athlytesports.com:8443",
#    "http://dev-srv.athlytesports.com",
   
#]

#CORS_ALLOWED_ORIGINS = [
#    "https://dev.athlytesports.com",
#    "https://dev-srv.athlytesports.com:8443",
#    "http://dev-srv.athlytesports.com",

#]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE',
    'OPTIONS',
]


CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
]
ROOT_URLCONF = 'playergame_poc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'playergame_poc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': config('DB_NAME'),
        'CLIENT': {
            'host': config('DB_HOST'),
            'username': config('DB_USER'),
            'password': config('DB_PASSWORD'),
            'authSource': config('DB_AUTH_SOURCE', default='admin'),
            'authMechanism': config('DB_AUTH_MECHANISM', default='SCRAM-SHA-256'),
        },
    }
}
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'athl_pilot',         # PostgreSQL DB name
        'USER': 'pilot_user',            # PostgreSQL username
        'PASSWORD': 'wPO7^1xT',    # PostgreSQL password
        'HOST': '18.216.7.109',            # Usually 'localhost' or IP
        'PORT': '5432',                          # Default PostgreSQL port
    },
    'postgres': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'athl_pilot',         # PostgreSQL DB name
        'USER': 'pilot_user',            # PostgreSQL username
        'PASSWORD': 'wPO7^1xT',    # PostgreSQL password
        'HOST': '18.216.7.109',            # Usually 'localhost' or IP
        'PORT': '5432',                          # Default PostgreSQL port
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
