mock_data = [
    {
        "gPersonId": 1,
        "position": "QB",
        "playerClass": "JR",
        "gameResult": "W",
        "playerName": "John Doe",
        "teamCode": "TC001",
        "teamName": "Team A",
        "opponentTeamCode": "OTC001",
        "opponentTeamName": "Team B",
        "gCompetitionId": 14,
        "academicSeason": "2024",
        "gConferenceId": 12,
        "teamConferenceName": "Conference A",
        "gOpponentConferenceId": 18,
        "opponentConferenceName": "Conference B",
        "gMatchId": 9896,
        "actualDate": "2024-10-05",
        "sReceptionYards": 60,
        "sRushingYardsNet": 80,
    },
    {
        "gPersonId": 2,
        "position": "RB",
        "playerClass": "SO",
        "gameResult": "L",
        "playerName": "Jane Smith",
        "teamCode": "TC002",
        "teamName": "Team C",
        "opponentTeamCode": "OTC002",
        "opponentTeamName": "Team D",
        "gCompetitionId": 15,
        "academicSeason": "2024",
        "gConferenceId": 13,
        "teamConferenceName": "Conference C",
        "gOpponentConferenceId": 19,
        "opponentConferenceName": "Conference D",
        "gMatchId": 9897,
        "actualDate": "2024-10-06",
        "sReceptionYards": 50,
        "sRushingYardsNet": 60,
    },
    {
        "gPersonId": 3,
        "position": "WR",
        "playerClass": "SR",
        "gameResult": "W",
        "playerName": "Mike Johnson",
        "teamCode": "TC003",
        "teamName": "Team E",
        "opponentTeamCode": "OTC003",
        "opponentTeamName": "Team F",
        "gCompetitionId": 16,
        "academicSeason": "2024",
        "gConferenceId": 14,
        "teamConferenceName": "Conference E",
        "gOpponentConferenceId": 20,
        "opponentConferenceName": "Conference F",
        "gMatchId": 9898,
        "actualDate": "2024-10-07",
        "sReceptionYards": 70,
        "sRushingYardsNet": 90,
    },
    {
        "gPersonId": 4,
        "position": "QB",
        "playerClass": "FR",
        "gameResult": "L",
        "playerName": "Chris White",
        "teamCode": "TC004",
        "teamName": "Team G",
        "opponentTeamCode": "OTC004",
        "opponentTeamName": "Team H",
        "gCompetitionId": 17,
        "academicSeason": "2024",
        "gConferenceId": 15,
        "teamConferenceName": "Conference G",
        "gOpponentConferenceId": 21,
        "opponentConferenceName": "Conference H",
        "gMatchId": 9899,
        "actualDate": "2024-10-08",
        "sReceptionYards": 80,
        "sRushingYardsNet": 110,
    },
    {
        "gPersonId": 5,
        "position": "RB",
        "playerClass": "SO",
        "gameResult": "W",
        "playerName": "Rachel Green",
        "teamCode": "TC005",
        "teamName": "Team I",
        "opponentTeamCode": "OTC005",
        "opponentTeamName": "Team J",
        "gCompetitionId": 18,
        "academicSeason": "2024",
        "gConferenceId": 16,
        "teamConferenceName": "Conference I",
        "gOpponentConferenceId": 22,
        "opponentConferenceName": "Conference J",
        "gMatchId": 9900,
        "actualDate": "2024-10-09",
        "sReceptionYards": 90,
        "sRushingYardsNet": 100,
    },
    {
        "gPersonId": 6,
        "position": "WR",
        "playerClass": "JR",
        "gameResult": "W",
        "playerName": "Emily Davis",
        "teamCode": "TC006",
        "teamName": "Team K",
        "opponentTeamCode": "OTC006",
        "opponentTeamName": "Team L",
        "gCompetitionId": 19,
        "academicSeason": "2024",
        "gConferenceId": 17,
        "teamConferenceName": "Conference K",
        "gOpponentConferenceId": 23,
        "opponentConferenceName": "Conference L",
        "gMatchId": 9901,
        "actualDate": "2024-10-10",
        "sReceptionYards": 120,
        "sRushingYardsNet": 150,
    },
    {
        "gPersonId": 7,
        "position": "QB",
        "playerClass": "SR",
        "gameResult": "L",
        "playerName": "Tom Lee",
        "teamCode": "TC007",
        "teamName": "Team M",
        "opponentTeamCode": "OTC007",
        "opponentTeamName": "Team N",
        "gCompetitionId": 20,
        "academicSeason": "2024",
        "gConferenceId": 18,
        "teamConferenceName": "Conference M",
        "gOpponentConferenceId": 24,
        "opponentConferenceName": "Conference N",
        "gMatchId": 9902,
        "actualDate": "2024-10-11",
        "sReceptionYards": 65,
        "sRushingYardsNet": 75,
    },
    {
        "gPersonId": 8,
        "position": "RB",
        "playerClass": "FR",
        "gameResult": "W",
        "playerName": "Sarah Wilson",
        "teamCode": "TC008",
        "teamName": "Team O",
        "opponentTeamCode": "OTC008",
        "opponentTeamName": "Team P",
        "gCompetitionId": 21,
        "academicSeason": "2024",
        "gConferenceId": 19,
        "teamConferenceName": "Conference O",
        "gOpponentConferenceId": 25,
        "opponentConferenceName": "Conference P",
        "gMatchId": 9903,
        "actualDate": "2024-10-12",
        "sReceptionYards": 55,
        "sRushingYardsNet": 85,
    },
    {
        "gPersonId": 9,
        "position": "WR",
        "playerClass": "SO",
        "gameResult": "L",
        "playerName": "Matthew Brown",
        "teamCode": "TC009",
        "teamName": "Team Q",
        "opponentTeamCode": "OTC009",
        "opponentTeamName": "Team R",
        "gCompetitionId": 22,
        "academicSeason": "2024",
        "gConferenceId": 20,
        "teamConferenceName": "Conference Q",
        "gOpponentConferenceId": 26,
        "opponentConferenceName": "Conference R",
        "gMatchId": 9904,
        "actualDate": "2024-10-13",
        "sReceptionYards": 40,
        "sRushingYardsNet": 65,
    },
    {
        "gPersonId": 10,
        "position": "QB",
        "playerClass": "SR",
        "gameResult": "W",
        "playerName": "Oliver King",
        "teamCode": "TC010",
        "teamName": "Team S",
        "opponentTeamCode": "OTC010",
        "opponentTeamName": "Team T",
        "gCompetitionId": 23,
        "academicSeason": "2024",
        "gConferenceId": 21,
        "teamConferenceName": "Conference S",
        "gOpponentConferenceId": 27,
        "opponentConferenceName": "Conference T",
        "gMatchId": 9905,
        "actualDate": "2024-10-14",
        "sReceptionYards": 75,
        "sRushingYardsNet": 95,
    },
    {
        "gPersonId": 11,
        "position": "WR",
        "playerClass": "SO",
        "gameResult": "L",
        "playerName": "Chris Garcia",
        "teamCode": "TC011",
        "teamName": "Team U",
        "opponentTeamCode": "OTC011",
        "opponentTeamName": "Team V",
        "gCompetitionId": 24,
        "academicSeason": "2024",
        "gConferenceId": 22,
        "teamConferenceName": "Conference U",
        "gOpponentConferenceId": 28,
        "opponentConferenceName": "Conference V",
        "gMatchId": 9906,
        "actualDate": "2024-10-15",
        "sReceptionYards": 85,
        "sRushingYardsNet": 115,
    },
    {
        "gPersonId": 12,
        "position": "RB",
        "playerClass": "FR",
        "gameResult": "W",
        "playerName": "Sophia Martinez",
        "teamCode": "TC012",
        "teamName": "Team W",
        "opponentTeamCode": "OTC012",
        "opponentTeamName": "Team X",
        "gCompetitionId": 25,
        "academicSeason": "2024",
        "gConferenceId": 23,
        "teamConferenceName": "Conference W",
        "gOpponentConferenceId": 29,
        "opponentConferenceName": "Conference X",
        "gMatchId": 9907,
        "actualDate": "2024-10-16",
        "sReceptionYards": 100,
        "sRushingYardsNet": 130,
    },
]
